# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: sw-builds
          event: fail
          template: basic_fail_1
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          command: aws s3 ls

workflows:
  welcome:
    jobs:
      - welcome/run
  deploy_and_notify:
    jobs:
      - deploy:
          context: SLACK_SECRETS
  aws-cli:
    jobs:
      - aws-cli-example:
          context: AWS_CREDENTIALS