version: 2.1
orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
  aws-cli: circleci/aws-cli@2.0.3
executors:
  docker-executor:
    docker:
      - image: cimg/python:3.9.6
jobs:
  setup-aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          command: aws --version
      - slack/notify:
          channel: sw-builds
          event: fail
          template: basic_fail_1
  plan:
    working_directory: ~/project
    executor: docker-executor
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          command: aws --version
      - run:
          name: Install Terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run:
          name: Terraform Init & Plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tf.plan
      - persist_to_workspace:
          root: ~/project
          paths:
            - ~/project/terraform/tf.plan
      - slack/notify:
          channel: sw-builds
          event: fail
          template: basic_fail_1
  apply:
    working_directory: ~/project
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - aws-cli/setup:
          profile-name: default
      - run:
          command: aws --version
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
          name: Install Terraform
      - run:
          name: terraform init and apply
          command: |
            cd terraform
            terraform init -input=false
            terraform apply --auto-approve tf.plan
      - slack/notify:
          channel: sw-builds
          event: fail
          template: basic_fail_1
  destroy:
    working_directory: ~/project
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - aws-cli/setup:
          profile-name: default
      - run:
          command: aws --version
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
          name: Install Terraform
      - run:
          name: terraform destroy
          command: |
            cd terraform
            terraform init -input=false
            terraform destroy --auto-approve tf.plan
      - slack/notify:
          channel: sw-builds
          event: fail
          template: basic_fail_1
workflows:
  version: 2.1
  Terraform Configuration:
    jobs:
      - plan:
          context:
            - AWS_CREDENTIALS
            - SLACK_SECRETS
      - require approval:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - require approval
          context:
            - AWS_CREDENTIALS
            - SLACK_SECRETS
      - destroy:
          requires:
            - apply
            - require approval
          context:
            - AWS_CREDENTIALS
            - SLACK_SECRETS